-- Seed initial affirmations with humorous content

insert into public.affirmations (text, category, author, status, is_featured, featured_date) values
  ('Your relentless pursuit of productivity is the most efficient way to ensure you never actually experience your own life.', 'Productivity', 'The Vibe Curator', 'approved', true, current_date),
  ('I am like a fine wine. I get more complex and harder to swallow with every passing year of my existence.', 'Self-Awareness', null, 'approved', false, current_date - interval '1 day'),
  ('You are like a majestic cactus: beautiful to look at, but generally better off when left entirely alone in a desert.', 'Relationships', null, 'approved', false, current_date - interval '2 days'),
  ('Your mediocrity is so consistent it has become a form of excellence.', 'Achievement', null, 'approved', false, current_date - interval '3 days'),
  ('The universe doesn''t have a plan for you, which is actually a huge relief for everyone involved.', 'Existential', null, 'approved', false, current_date - interval '4 days'),
  ('Breathe in the expectations of others. Breathe out a mild shrug.', 'Wellness', null, 'approved', false, current_date - interval '5 days'),
  ('You are the main character in a very confusing indie film that no one has seen yet.', 'Identity', null, 'approved', false, current_date - interval '6 days'),
  ('Silence is just a sound you haven''t ruined yet.', 'Mindfulness', null, 'approved', false, current_date - interval '7 days'),
  ('It''s okay to peaked in high school; it makes the rest of your life very consistent.', 'Growth', null, 'approved', false, current_date - interval '8 days'),
  ('Your inner child is actually a 45-year-old accountant named Dave.', 'Self-Discovery', null, 'approved', false, current_date - interval '9 days'),
  ('My inner peace is a very expensive luxury that I currently cannot afford, but I look great in the brochure.', 'Wealth', null, 'approved', false, current_date - interval '10 days'),
  ('I inhale confidence and exhale the overwhelming urge to apologize for things I didn''t actually do.', 'Daily Ritual', null, 'approved', false, current_date - interval '11 days'),
  ('I am a masterpiece of procrastination, meticulously crafting my destiny tomorrow afternoon.', 'Productivity', null, 'approved', false, current_date - interval '12 days'),
  ('Today, I choose to be the main character in a movie that goes straight to VHS and becomes a cult classic.', 'Identity', null, 'approved', false, current_date - interval '13 days'),
  ('If you ever find yourself being chased by a pack of wild dogs, try to act like you''re their leader. If that doesn''t work, try to act like a giant, angry cat. But most importantly, try to be faster than the person next to you.', 'Survival', null, 'approved', true, current_date - interval '14 days'),
  ('We spend the first half of our lives trying to be noticed, and the second half trying to be left alone.', 'Philosophy', null, 'approved', false, current_date - interval '15 days'),
  ('Productivity is just the art of looking busy enough to avoid the crushing weight of stillness.', 'Satire', null, 'approved', false, current_date - interval '16 days'),
  ('I am not late. I am arriving at precisely the moment my presence is most needed to provide an air of chaotic mystery.', 'Time Management', null, 'approved', false, current_date - interval '17 days'),
  ('My houseplants are not dying; they are successfully transitioning into minimalist hay sculptures.', 'Optimism', null, 'approved', false, current_date - interval '18 days'),
  ('The synergy of our collective silence is the only deliverable that matters this quarter.', 'Corporate Ennui', null, 'approved', false, current_date - interval '19 days'),
  ('Deleting the app is the new meditation.', 'Digital Decay', null, 'approved', false, current_date - interval '20 days'),
  ('I manifested a parking spot today. It was three miles away, but the universe clearly wants me to have great calves.', 'Manifestation', null, 'approved', false, current_date - interval '21 days'),
  ('My inner peace is so profound that I am now officially bored of my own serenity. I am considering picking a fight with a local swan just to feel alive again.', 'Mindfulness', null, 'approved', false, current_date - interval '22 days'),
  ('Your trauma is a vintage accessory. Wear it with a blazer and pretend it was expensive.', 'Self-Care', null, 'approved', false, current_date - interval '23 days'),
  ('The sun sets on your problems, but they''ll be back at breakfast with a vengeance.', 'Optimism', null, 'approved', false, current_date - interval '24 days'),
  ('I am currently accepting apologies for things I haven''t even found out about yet. Efficient living.', 'Efficiency', null, 'approved', false, current_date - interval '25 days'),
  ('I am a financial wizard. I make money disappear and replace it with small, useless objects from antique stores.', 'Wealth', null, 'approved', false, current_date - interval '26 days'),
  ('My second cup of coffee is not a beverage; it is a legal requirement for my participation in this reality.', 'Morning Routine', null, 'approved', false, current_date - interval '27 days'),
  ('If a meeting happens and no one records the minutes, did we actually waste an hour?', 'Corporate Ennui', null, 'approved', false, current_date - interval '28 days'),
  ('Is it ''working'' if you''re just organizing the list of things you aren''t doing?', 'Productivity', null, 'approved', false, current_date - interval '29 days')
on conflict do nothing;
